"""2.2

Revision ID: 769625c63571
Revises: 334bb3846030
Create Date: 2021-03-30 11:54:47.074688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769625c63571'
down_revision = '334bb3846030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_book_category_relation', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_book_category_relation', 'id')
    # ### end Alembic commands ###
